# Generated by Django 5.0.6 on 2024-06-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('all_task', 'Can view all tasks')]},
        ),
    ]
