# Generated by Django 5.0.6 on 2024-06-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('all_employees', 'Can view all employees')]},
        ),
    ]
