# Generated by Django 5.0.6 on 2024-06-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
