version: '3.8'

services:
  web:
    build: ./taskmanager
    container_name: taskmanager_api
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - default

  db:
    image: postgres:16
    container_name: pg_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /pgdata:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    networks:
      - default

networks:
  default:
    driver: bridge

